### ISSUE TITLE
[Vue warn]: Property or method "hide" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by IvanaPolonijo** [KristijanCetina/payingCustomer#106]
Javlja nam se hrpa errora ovog tipa
https://gyazo.com/2d84230c176a21d2703abd6725e6ae8e

počistiti...

**Comment by Marko-Tomljanovic** [comment]
Nisam dobio isti error, no počistio jesam što sam smatrao da je uzrok. Stavljam issue na "Tessting", ako se isti opet pojavi vratiti na "In progress".
