### ISSUE TITLE
AWS account?

### ISSUE THREAD

**Issue by IvanaPolonijo** [KristijanCetina/payingCustomer#11]
Pitanjce ...hoćemo li koristiti AWS (amazon) za bazu i server?

Ja (Ivana) sam pokrenula svoju registraciju na www.awseducate.com  jer (a) mi je super iskorištavati te besplatne stvari sad dok mogu kao studentica :) i (b) da vidim što se nudi i hićemo li to iskoristiti ;)

Kristijan, jel' bi ti mogao pregledati i donjeti neke odluke kako ćemo po tom arhitektonskom pitanju :P

**Comment by KristijanCetina** [comment]
To nije loša ideja ali za počekat ćemo koristiti [Firebase](https://firebase.google.com/) kao bazu i backend.
Nakon toga možemo razmišljati o prelasku na AWS (koji bi bilo fora proučiti i naučiti).
