### ISSUE TITLE
git i Github desktop instalacija

### ISSUE THREAD

**Issue by IvanaPolonijo** [KristijanCetina/payingCustomer#2]
Svi članovi tima to moraju učiniti - tko zadnji potvrdi neka zatvori Issue

**Comment by IvanaPolonijo** [comment]
rešeno...i znam da su već svi, ali se malo naviknimo i na ovo ;)

**Comment by Marko-Tomljanovic** [comment]
Instalirano 👍

**Comment by KristijanCetina** [comment]
svi su to napravili pa zatvaram issus #2
