### ISSUE TITLE
Prototip i koncept projekta

### ISSUE THREAD

**Issue by IvanaPolonijo** [KristijanCetina/payingCustomer#6]
PI zahtjeva predaju Prototip i koncept projekta

**Comment by IvanaPolonijo** [comment]
U čemu se izrađuje protip i koncept? Rok za predaju je 11/11/2020

**Comment by KristijanCetina** [comment]
Ja vjerujem kako će o tome biti riječi na sljedećem predavanju.
Znam da se spominjala [figma](https://www.figma.com/) ali neznam dalje od toga.

**Comment by IvanaPolonijo** [comment]
Okay - malo si u međuvremenu bacimo pogled na https://www.figma.com/prototyping/...

Caka je u tome da je besplatno samo do dva editora...a educational paket mi otvara blank page :D

**Comment by IvanaPolonijo** [comment]
okay - uspjela si napraviti educator profil... @KristijanCetina  i @Marko-Tomljanovic  napravite s faks emailovima i navedite da ste na University of Pula (imaju na listi)
Ja temeljem uputa na https://help.figma.com/hc/en-us/articles/360041061214-Verify-your-Education-status radim projekt pa ću vam poslati poziv...pa da čisto prije nego kak spada krenemo isto malo kopamo po  alatu ;)

**Comment by Marko-Tomljanovic** [comment]
Dobio poziv, uspio napraviti profil sa email-om od faksa. Izgleda dobro, sad se treba pozabaviti s figmom :)

**Comment by IvanaPolonijo** [comment]
Status update - osnove dizajna postavljene u Figmi

U procesu je izrada dijagrama kako bi se između ostalog zgotovio u prototip

**Comment by IvanaPolonijo** [comment]
Use case diagram je zgotovljen - finalne dorade na prototipu su u tijeku

**Comment by IvanaPolonijo** [comment]
@Marko-Tomljanovic ...pingaj za sve što nije jasno :) 

1/ About us 
![image](https://user-images.githubusercontent.com/73447189/99885866-32fa7e80-2c38-11eb-9ea0-cd1e3f185d3f.png)
 --> dodaj lorem ipsum s gumbom na pregled planova (choose plan). Slično onom pozivu na akciju na main page

2/ ajmo ovu navigaciju 
![image](https://user-images.githubusercontent.com/73447189/99885530-dac27d00-2c35-11eb-8a0a-3f4af800f629.png) 
pretvoriti u subscription/mypayments/calendar/news
--> pa onda
subscription -> update your plan sadržaj
mypayments -> popis računa sa stanjem (je li plaćen ili ne te datum izdavanja) (ovo bi trebalo imati link da se skine račun...o tom po tom  kad vidimo koliko će nam API dati) 
calendar --> doslovno 7 dana u tjednu (može statično slika) s nekim rasporedom
news --> vijesti jedna ispod druge s title, date i body

3/ U top navi
![image](https://user-images.githubusercontent.com/73447189/99885871-43125e00-2c38-11eb-9b06-88a96dd3d888.png)
ubaciti news i calendar

_Ako se stigne prije predaje:_
_4/ treba nam dash i za managera koji ima u lijevom navi korisnici/pretplate/placanja/news/calendar
--> korisnici: popis korisnika s mogućnosti filtriranja ili searcha 
--> pretplate: pregled tipova pretplati i njhovo editiranje
--> news: pregled novosti. mogućnost dodavanja i brisanja newsa. Dodavanje je popup (lightbox) gdje manager ubaci naslov, date i body text_

**Comment by Marko-Tomljanovic** [comment]
Finalne dorade u prototipu su napravljene te se priprema za predaju uz dijagrame.
