### ISSUE TITLE
Komponenta za vijesti

### ISSUE THREAD

**Issue by IvanaPolonijo** [KristijanCetina/payingCustomer#62]
Pojavljivat će se kao takva na News i na News_dash
Mora sadržavati:
Title
Date
Body

p.s. Bit će varijanta na temu za admine da mogu editirati i stvarati nove, ali o tom po tom ...

**Comment by Marko-Tomljanovic** [comment]
Dovršeno, ide na testiranje.

**Comment by IvanaPolonijo** [comment]
preuzimam na testiranje

**Comment by IvanaPolonijo** [comment]
@Marko-Tomljanovic ovo izgleda super, no daj vidi kao je kad ima recimo 10 kartica (to je recimo max koji bi prikazivali) .
Predlažem da se implementira neka paginacija da prikazujemo recimo 4 po stranici ...
+ probaj dodati isto na https://payingcustomer.netlify.app/News_dash da vidimo kako se ponaša

**Comment by Marko-Tomljanovic** [comment]
Oke, bacam se na posao

**Comment by IvanaPolonijo** [comment]
btw @Marko-Tomljanovic da ti se ne petljam na stranicu - možeš sa subscription stranice pokkupiti generalni setup(grid i navigaciju)

**Comment by Marko-Tomljanovic** [comment]
Proslijeđeno na testiranje, javi ako sta treba doraditi, imam novi branch za to.

**Comment by IvanaPolonijo** [comment]
komponenta super  - zatvaram ticket. sljedeća faza će biti omogućiti stvaranje novih adminima
