### ISSUE TITLE
Prijava projekta

### ISSUE THREAD

**Issue by IvanaPolonijo** [KristijanCetina/payingCustomer#7]
**Koraci** 

1. Prvo se prijavljuje tim (odaberite naziv) i projekt (ili sudjelovanje na IT contestu) - prijavljuje bilo tko iz tima

2. Zatim svaki student prijavljuje sudjelovanje u timovu iz prvog koraka gdje navodi svoju ulogu.

---------------------------

**Comment by IvanaPolonijo** [comment]
- [x] @KristijanCetina je li prijavljen projekt na PII? 

---------------

Na to onda treba dogovoriti uloge ... načelno :) ...

### ROK je 06/11/2020

**Comment by KristijanCetina** [comment]
> ROK je 06/11/2020

ako glumimo redovne studente onda je to daleko cjelu vječnost :-)
Biti će uskoro ...

**Comment by KristijanCetina** [comment]
@IvanaPolonijo @Marko-Tomljanovic 
Projekt je prijavljen pa se možete i vi prijaviti u njega. naziv tima je oldiesButGoldie.

Kada se prijavite javite ovdje tako da kada svi to obavimo da možemo zatvoriti ticket

**Comment by Marko-Tomljanovic** [comment]
Javljam da sam prijavljen u tim oldiesButGoldie.

**Comment by IvanaPolonijo** [comment]
all sorted :)
