### ISSUE TITLE
Popis želja

### ISSUE THREAD

**Issue by IvanaPolonijo** [KristijanCetina/payingCustomer#8]
Popisati prvi set želja po pitanju feature. na https://github.com/KristijanCetina/payingCustomer/wiki/Popis-%C5%BEelja
Go wild...filtrirat ćemo kako napredujemo :)

**Comment by IvanaPolonijo** [comment]
@Marko-Tomljanovic ne vidim ništa od tebe još...

**Comment by Marko-Tomljanovic** [comment]
@IvanaPolonijo dopunjeno :)

**Comment by IvanaPolonijo** [comment]
super!

Zatvorit ću issue no neka nam taj iki ostane da si tamo slažemo i dopunjavamo za sprintove...
