### ISSUE TITLE
Desno gore kad si ulogiran (https://gyazo.com/3e50851cfec1629cc4dd03bd0a4b56e0) ... da bude dropdown?

### ISSUE THREAD

**Issue by IvanaPolonijo** [KristijanCetina/payingCustomer#83]
@Marko prema dogovoru ovo istiliziraj da bude padajući s edit i logout (sa ili bez neke ikone umjesto hello)

**Comment by Marko-Tomljanovic** [comment]
@IvanaPolonijo spremno za testiranje. 

![dropdown](https://user-images.githubusercontent.com/56721240/104525062-b49ad700-55ff-11eb-974d-04a0ca18a68d.PNG)
